export type CategoryId = "coffee" | "noncoffee" | "tea" | "smoothie" | "dessert"

export interface Category {
  id: CategoryId
  name: string
  /** lucide icon name used in the UI */
  icon: string
}

export interface MenuItem {
  id: string
  name: string
  category: CategoryId
  price: number
  description: string
  /** lucide icon name shown when there is no photo */
  icon: string
  /** path under /public for items that have a real photo */
  image?: string
  /** can be served hot / iced */
  temperatures: ("hot" | "ice")[]
  /** offers size options */
  hasSize: boolean
  /** keywords used for natural-language intent matching */
  keywords: string[]
}

export const categories: Category[] = [
  { id: "coffee", name: "커피", icon: "Coffee" },
  { id: "noncoffee", name: "논커피", icon: "CupSoda" },
  { id: "tea", name: "차", icon: "Leaf" },
  { id: "smoothie", name: "스무디 · 에이드", icon: "Blend" },
  { id: "dessert", name: "디저트", icon: "Cake" },
]

export const categoryMap: Record<CategoryId, Category> = categories.reduce(
  (acc, c) => {
    acc[c.id] = c
    return acc
  },
  {} as Record<CategoryId, Category>,
)

// price helper
const w = (n: number) => n

export const menuItems: MenuItem[] = [
  // ── 커피 (12) ─────────────────────────────────────────
  {
    id: "americano",
    name: "아메리카노",
    category: "coffee",
    price: w(3000),
    description: "진하고 깔끔한 기본 커피",
    icon: "Coffee",
    image: "/menu/americano.png",
    temperatures: ["hot", "ice"],
    hasSize: true,
    keywords: ["커피", "아메리카노", "쓴", "진한", "기본", "블랙"],
  },
  {
    id: "cafe-latte",
    name: "카페라떼",
    category: "coffee",
    price: w(3800),
    description: "부드러운 우유가 가득한 커피",
    icon: "Coffee",
    image: "/menu/cafe-latte.png",
    temperatures: ["hot", "ice"],
    hasSize: true,
    keywords: ["라떼", "우유", "부드러운", "커피", "고소한"],
  },
  {
    id: "cappuccino",
    name: "카푸치노",
    category: "coffee",
    price: w(4000),
    description: "풍성한 우유 거품이 올라간 커피",
    icon: "Coffee",
    image: "/menu/cappuccino.png",
    temperatures: ["hot", "ice"],
    hasSize: true,
    keywords: ["카푸치노", "거품", "우유", "커피"],
  },
  {
    id: "vanilla-latte",
    name: "바닐라라떼",
    category: "coffee",
    price: w(4300),
    description: "달콤한 바닐라 향 커피",
    icon: "Coffee",
    temperatures: ["hot", "ice"],
    hasSize: true,
    keywords: ["바닐라", "달콤한", "라떼", "단", "커피"],
  },
  {
    id: "caramel-macchiato",
    name: "카라멜마끼아또",
    category: "coffee",
    price: w(4700),
    description: "달콤 쌉싸름한 카라멜 커피",
    icon: "Coffee",
    temperatures: ["hot", "ice"],
    hasSize: true,
    keywords: ["카라멜", "달콤한", "단", "마끼아또", "커피"],
  },
  {
    id: "cafe-mocha",
    name: "카페모카",
    category: "coffee",
    price: w(4500),
    description: "초콜릿이 들어간 달콤한 커피",
    icon: "Coffee",
    temperatures: ["hot", "ice"],
    hasSize: true,
    keywords: ["초콜릿", "초코", "모카", "달콤한", "단", "커피"],
  },
  {
    id: "espresso",
    name: "에스프레소",
    category: "coffee",
    price: w(2800),
    description: "가장 진한 커피 원액",
    icon: "Coffee",
    temperatures: ["hot"],
    hasSize: false,
    keywords: ["에스프레소", "진한", "쓴", "커피", "샷"],
  },
  {
    id: "con-panna",
    name: "콘파나",
    category: "coffee",
    price: w(3500),
    description: "에스프레소 위에 크림을 올린 커피",
    icon: "Coffee",
    temperatures: ["hot"],
    hasSize: false,
    keywords: ["크림", "콘파나", "달콤한", "커피"],
  },
  {
    id: "hazelnut-latte",
    name: "헤이즐넛라떼",
    category: "coffee",
    price: w(4300),
    description: "고소한 헤이즐넛 향 커피",
    icon: "Coffee",
    temperatures: ["hot", "ice"],
    hasSize: true,
    keywords: ["헤이즐넛", "고소한", "견과", "라떼", "커피"],
  },
  {
    id: "cold-brew",
    name: "콜드브루",
    category: "coffee",
    price: w(4200),
    description: "차갑게 내린 부드러운 커피",
    icon: "Coffee",
    temperatures: ["ice"],
    hasSize: true,
    keywords: ["콜드브루", "차가운", "시원한", "부드러운", "커피"],
  },
  {
    id: "decaf-americano",
    name: "디카페인 아메리카노",
    category: "coffee",
    price: w(3500),
    description: "카페인을 줄인 편안한 커피",
    icon: "Coffee",
    temperatures: ["hot", "ice"],
    hasSize: true,
    keywords: ["디카페인", "카페인없는", "아메리카노", "커피", "저녁"],
  },
  {
    id: "dolce-latte",
    name: "돌체라떼",
    category: "coffee",
    price: w(4800),
    description: "연유가 들어간 아주 달콤한 라떼",
    icon: "Coffee",
    temperatures: ["hot", "ice"],
    hasSize: true,
    keywords: ["연유", "돌체", "아주단", "달콤한", "라떼", "커피"],
  },

  // ── 논커피 (10) ───────────────────────────────────────
  {
    id: "choco-latte",
    name: "초코라떼",
    category: "noncoffee",
    price: w(4300),
    description: "진한 초콜릿 우유 음료",
    icon: "CupSoda",
    image: "/menu/choco-latte.png",
    temperatures: ["hot", "ice"],
    hasSize: true,
    keywords: ["초코", "초콜릿", "달콤한", "단", "우유", "라떼", "커피아닌"],
  },
  {
    id: "choco-shake",
    name: "초코쉐이크",
    category: "noncoffee",
    price: w(5300),
    description: "시원하게 갈아 만든 진한 초코 음료",
    icon: "CupSoda",
    image: "/menu/choco-shake.png",
    temperatures: ["ice"],
    hasSize: true,
    keywords: ["초코", "초콜릿", "달콤한", "단", "시원한", "차가운", "쉐이크", "우유", "커피아닌"],
  },
  {
    id: "green-tea-latte",
    name: "녹차라떼",
    category: "noncoffee",
    price: w(4500),
    description: "고소하고 진한 녹차 우유",
    icon: "CupSoda",
    image: "/menu/green-tea-latte.png",
    temperatures: ["hot", "ice"],
    hasSize: true,
    keywords: ["녹차", "말차", "고소한", "우유", "라떼", "커피아닌"],
  },
  {
    id: "sweet-potato-latte",
    name: "고구마라떼",
    category: "noncoffee",
    price: w(4800),
    description: "달콤하고 든든한 고구마 우유",
    icon: "CupSoda",
    image: "/menu/sweet-potato-latte.png",
    temperatures: ["hot", "ice"],
    hasSize: true,
    keywords: ["고구마", "달콤한", "단", "든든한", "우유", "라떼", "커피아닌"],
  },
  {
    id: "milk-tea",
    name: "밀크티",
    category: "noncoffee",
    price: w(4500),
    description: "홍차와 우유가 어우러진 음료",
    icon: "CupSoda",
    temperatures: ["hot", "ice"],
    hasSize: true,
    keywords: ["밀크티", "홍차", "우유", "달콤한", "커피아닌"],
  },
  {
    id: "strawberry-latte",
    name: "딸기라떼",
    category: "noncoffee",
    price: w(4800),
    description: "상큼한 딸기와 우유",
    icon: "CupSoda",
    temperatures: ["ice"],
    hasSize: true,
    keywords: ["딸기", "상큼한", "달콤한", "우유", "라떼", "커피아닌"],
  },
  {
    id: "black-sesame-latte",
    name: "흑임자라떼",
    category: "noncoffee",
    price: w(4800),
    description: "고소한 흑임자 우유 음료",
    icon: "CupSoda",
    temperatures: ["hot", "ice"],
    hasSize: true,
    keywords: ["흑임자", "고소한", "우유", "라떼", "커피아닌", "어르신"],
  },
  {
    id: "yogurt-smoothie",
    name: "요거트 음료",
    category: "noncoffee",
    price: w(4500),
    description: "새콤달콤 부드러운 요거트",
    icon: "CupSoda",
    temperatures: ["ice"],
    hasSize: true,
    keywords: ["요거트", "새콤한", "상큼한", "달콤한", "커피아닌"],
  },
  {
    id: "hot-chocolate",
    name: "핫초코",
    category: "noncoffee",
    price: w(4000),
    description: "따뜻하고 달콤한 초콜릿 음료",
    icon: "CupSoda",
    temperatures: ["hot"],
    hasSize: true,
    keywords: ["핫초코", "초코", "초콜릿", "따뜻한", "달콤한", "단", "커피아닌"],
  },
  {
    id: "grain-latte",
    name: "곡물라떼",
    category: "noncoffee",
    price: w(4500),
    description: "구수한 곡물과 우유",
    icon: "CupSoda",
    temperatures: ["hot", "ice"],
    hasSize: true,
    keywords: ["곡물", "미숫가루", "구수한", "고소한", "우유", "어르신", "커피아닌"],
  },
  {
    id: "banana-milk",
    name: "바나나우유",
    category: "noncoffee",
    price: w(4300),
    description: "달콤하고 부드러운 바나나 우유",
    icon: "CupSoda",
    temperatures: ["ice"],
    hasSize: true,
    keywords: ["바나나", "달콤한", "부드러운", "우유", "커피아닌"],
  },

  // ── 차 (8) ────────────────────────────────────────────
  {
    id: "chamomile",
    name: "캐모마일 차",
    category: "tea",
    price: w(3800),
    description: "은은하고 편안한 꽃차",
    icon: "Leaf",
    image: "/menu/chamomile.png",
    temperatures: ["hot", "ice"],
    hasSize: false,
    keywords: ["캐모마일", "꽃차", "편안한", "잠", "차", "따뜻한"],
  },
  {
    id: "peppermint",
    name: "페퍼민트 차",
    category: "tea",
    price: w(3800),
    description: "상쾌하고 시원한 허브차",
    icon: "Leaf",
    image: "/menu/peppermint.png",
    temperatures: ["hot", "ice"],
    hasSize: false,
    keywords: ["페퍼민트", "민트", "상쾌한", "시원한", "허브", "차"],
  },
  {
    id: "citron-tea",
    name: "유자차",
    category: "tea",
    price: w(4000),
    description: "새콤달콤 비타민 가득 유자",
    icon: "Leaf",
    image: "/menu/citron-tea.png",
    temperatures: ["hot", "ice"],
    hasSize: false,
    keywords: ["유자", "새콤한", "달콤한", "비타민", "감기", "차", "어르신"],
  },
  {
    id: "ginger-tea",
    name: "생강차",
    category: "tea",
    price: w(4000),
    description: "몸을 따뜻하게 하는 생강차",
    icon: "Leaf",
    temperatures: ["hot"],
    hasSize: false,
    keywords: ["생강", "따뜻한", "감기", "몸", "차", "어르신"],
  },
  {
    id: "jujube-tea",
    name: "대추차",
    category: "tea",
    price: w(4200),
    description: "달큰하고 건강한 대추차",
    icon: "Leaf",
    temperatures: ["hot"],
    hasSize: false,
    keywords: ["대추", "건강한", "달콤한", "따뜻한", "차", "어르신"],
  },
  {
    id: "green-tea",
    name: "녹차",
    category: "tea",
    price: w(3800),
    description: "맑고 깔끔한 우리 녹차",
    icon: "Leaf",
    temperatures: ["hot", "ice"],
    hasSize: false,
    keywords: ["녹차", "깔끔한", "맑은", "차"],
  },
  {
    id: "black-tea",
    name: "홍차",
    category: "tea",
    price: w(3800),
    description: "향긋하고 진한 홍차",
    icon: "Leaf",
    temperatures: ["hot", "ice"],
    hasSize: false,
    keywords: ["홍차", "향긋한", "진한", "차"],
  },
  {
    id: "rooibos",
    name: "루이보스 차",
    category: "tea",
    price: w(4000),
    description: "카페인 없는 순한 차",
    icon: "Leaf",
    temperatures: ["hot", "ice"],
    hasSize: false,
    keywords: ["루이보스", "카페인없는", "순한", "편안한", "차"],
  },

  // ── 스무디 · 에이드 (8) ───────────────────────────────
  {
    id: "strawberry-smoothie",
    name: "딸기 스무디",
    category: "smoothie",
    price: w(5300),
    description: "딸기를 갈아 만든 시원한 음료",
    icon: "Blend",
    image: "/menu/strawberry-smoothie.png",
    temperatures: ["ice"],
    hasSize: true,
    keywords: ["딸기", "스무디", "시원한", "차가운", "상큼한", "달콤한", "과일"],
  },
  {
    id: "mango-smoothie",
    name: "망고 스무디",
    category: "smoothie",
    price: w(5500),
    description: "달콤한 망고를 가득 담은 스무디",
    icon: "Blend",
    image: "/menu/mango-smoothie.png",
    temperatures: ["ice"],
    hasSize: true,
    keywords: ["망고", "스무디", "시원한", "차가운", "달콤한", "과일"],
  },
  {
    id: "grapefruit-ade",
    name: "자몽 에이드",
    category: "smoothie",
    price: w(5000),
    description: "상큼 쌉싸름한 자몽 탄산음료",
    icon: "Blend",
    image: "/menu/grapefruit-ade.png",
    temperatures: ["ice"],
    hasSize: true,
    keywords: ["자몽", "에이드", "탄산", "시원한", "차가운", "상큼한", "과일"],
  },
  {
    id: "blueberry-smoothie",
    name: "블루베리 스무디",
    category: "smoothie",
    price: w(5500),
    description: "새콤달콤 블루베리 스무디",
    icon: "Blend",
    temperatures: ["ice"],
    hasSize: true,
    keywords: ["블루베리", "스무디", "시원한", "차가운", "새콤한", "과일"],
  },
  {
    id: "lemon-ade",
    name: "레몬 에이드",
    category: "smoothie",
    price: w(4800),
    description: "톡 쏘는 새콤한 레몬 탄산",
    icon: "Blend",
    temperatures: ["ice"],
    hasSize: true,
    keywords: ["레몬", "에이드", "탄산", "시원한", "새콤한", "상큼한"],
  },
  {
    id: "green-grape-ade",
    name: "청포도 에이드",
    category: "smoothie",
    price: w(5000),
    description: "달콤한 청포도 탄산음료",
    icon: "Blend",
    temperatures: ["ice"],
    hasSize: true,
    keywords: ["청포도", "포도", "에이드", "탄산", "시원한", "달콤한"],
  },
  {
    id: "plum-ade",
    name: "매실 에이드",
    category: "smoothie",
    price: w(4800),
    description: "새콤달콤 매실 탄산음료",
    icon: "Blend",
    temperatures: ["ice"],
    hasSize: true,
    keywords: ["매실", "에이드", "탄산", "시원한", "새콤한", "어르신"],
  },
  {
    id: "peach-smoothie",
    name: "복숭아 스무디",
    category: "smoothie",
    price: w(5500),
    description: "향긋한 복숭아 스무디",
    icon: "Blend",
    temperatures: ["ice"],
    hasSize: true,
    keywords: ["복숭아", "스무디", "시원한", "차가운", "달콤한", "과일"],
  },

  // ── 디저트 (12) ───────────────────────────────────────
  {
    id: "cheesecake",
    name: "치즈케이크",
    category: "dessert",
    price: w(5500),
    description: "부드럽고 진한 치즈 케이크",
    icon: "Cake",
    image: "/menu/cheesecake.png",
    temperatures: [],
    hasSize: false,
    keywords: ["치즈", "케이크", "디저트", "달콤한", "부드러운"],
  },
  {
    id: "tiramisu",
    name: "티라미수",
    category: "dessert",
    price: w(5800),
    description: "커피 향 가득한 부드러운 케이크",
    icon: "Cake",
    image: "/menu/tiramisu.png",
    temperatures: [],
    hasSize: false,
    keywords: ["티라미수", "케이크", "디저트", "커피", "달콤한"],
  },
  {
    id: "choco-cookie",
    name: "초코 쿠키",
    category: "dessert",
    price: w(3000),
    description: "바삭하고 달콤한 초콜릿 쿠키",
    icon: "Cookie",
    image: "/menu/choco-cookie.png",
    temperatures: [],
    hasSize: false,
    keywords: ["초코", "초콜릿", "쿠키", "과자", "디저트", "바삭한", "달콤한"],
  },
  {
    id: "croissant",
    name: "크루아상",
    category: "dessert",
    price: w(3800),
    description: "겹겹이 바삭한 버터 빵",
    icon: "Croissant",
    temperatures: [],
    hasSize: false,
    keywords: ["크루아상", "빵", "버터", "바삭한", "디저트", "베이커리"],
  },
  {
    id: "scone",
    name: "스콘",
    category: "dessert",
    price: w(3500),
    description: "담백하고 고소한 구움과자",
    icon: "Croissant",
    temperatures: [],
    hasSize: false,
    keywords: ["스콘", "빵", "담백한", "고소한", "디저트", "베이커리"],
  },
  {
    id: "chocolate-cake",
    name: "초코 케이크",
    category: "dessert",
    price: w(5800),
    description: "진한 초콜릿 케이크",
    icon: "Cake",
    temperatures: [],
    hasSize: false,
    keywords: ["초코", "초콜릿", "케이크", "디저트", "달콤한", "단"],
  },
  {
    id: "macaron",
    name: "마카롱",
    category: "dessert",
    price: w(2800),
    description: "쫄깃하고 달콤한 한입 과자",
    icon: "Cookie",
    temperatures: [],
    hasSize: false,
    keywords: ["마카롱", "달콤한", "단", "디저트", "과자"],
  },
  {
    id: "madeleine",
    name: "마들렌",
    category: "dessert",
    price: w(3000),
    description: "촉촉하고 부드러운 구움과자",
    icon: "Cookie",
    temperatures: [],
    hasSize: false,
    keywords: ["마들렌", "구움과자", "촉촉한", "부드러운", "디저트"],
  },
  {
    id: "egg-tart",
    name: "에그타르트",
    category: "dessert",
    price: w(3500),
    description: "바삭한 겉, 부드러운 속 커스터드",
    icon: "Cookie",
    temperatures: [],
    hasSize: false,
    keywords: ["에그타르트", "타르트", "커스터드", "달콤한", "디저트"],
  },
  {
    id: "red-bean-bread",
    name: "단팥빵",
    category: "dessert",
    price: w(3000),
    description: "달콤한 팥이 가득한 부드러운 빵",
    icon: "Croissant",
    temperatures: [],
    hasSize: false,
    keywords: ["단팥빵", "팥", "빵", "달콤한", "디저트", "어르신"],
  },
  {
    id: "rice-cake",
    name: "꿀떡",
    category: "dessert",
    price: w(3000),
    description: "쫄깃하고 달콤한 우리 떡",
    icon: "Cookie",
    temperatures: [],
    hasSize: false,
    keywords: ["꿀떡", "떡", "쫄깃한", "달콤한", "디저트", "어르신"],
  },
  {
    id: "waffle",
    name: "와플",
    category: "dessert",
    price: w(4500),
    description: "겉바속촉 따끈한 와플",
    icon: "Cake",
    temperatures: [],
    hasSize: false,
    keywords: ["와플", "따뜻한", "달콤한", "디저트", "베이커리"],
  },
]

export function getItemsByCategory(category: CategoryId): MenuItem[] {
  return menuItems.filter((item) => item.category === category)
}

export function getItemById(id: string): MenuItem | undefined {
  return menuItems.find((item) => item.id === id)
}

export function formatWon(n: number): string {
  return n.toLocaleString("ko-KR") + "원"
}
